POST method was created for adding reviews with serializer and views
ita-social-projects/BeatyProject pull request #179
Opened 2022-05-25 20:24 UTC by pazuzu-ua

A view for a POST method was created to post a Review. A serializer and tests were added for this view.
Closes #170
Closes #155
Closed #136
Closes #138

2022-05-26 07:59 UTC, Misha86 commented on beauty/api/serializers/serializers_review.py
> +    def update(self, instance, validated_data):
does It not work without reloading this method?

2022-05-26 08:05 UTC, Misha86 commented on beauty/api/tests/test_POST_method_to_add_review.py
> +        return super().setUp()
setUp returned super().setUp().
For what does it need?

2022-05-26 08:11 UTC, Misha86 reviewed
Some comments are only not understanding how it works.

2022-05-26 08:15 UTC, Deer-WarLord commented on beauty/api/tests/test_POST_method_to_add_review.py
> +        return super().setUp()
inheritance (call super) is needed if only you want to use functionality from the base class setUp. It should be used at the beginning of the method and never in the return statement

2022-05-26 08:19 UTC, Deer-WarLord commented on beauty/api/tests/test_POST_method_to_add_review.py
> +            data={'text_body': 'I am not a logged User', 'rating': 3}
the path should be simplified using Django features of the routing mechanism. Try to avoid the full URL paths by replacing the host with settings constant or making paths relative

2022-05-26 08:23 UTC, Deer-WarLord commented on beauty/api/views.py
> +        """This is a POST method of the view"""
Is there a need to rewrite standard post method by the implementation beloved?

2022-05-28 14:46 UTC, pazuzu-ua commented on beauty/api/serializers/serializers_review.py
> +    def update(self, instance, validated_data):
Reasonable thing. Fixed, thank you!

2022-05-28 14:47 UTC, pazuzu-ua commented on beauty/api/tests/test_POST_method_to_add_review.py
> +        return super().setUp()
Noted with thanks, I have investigated this and already fixed

2022-05-28 14:47 UTC, pazuzu-ua commented on beauty/api/tests/test_POST_method_to_add_review.py
> +            data={'text_body': 'I am not a logged User', 'rating': 3}
I have rewritten this, thank you for the tip!

2022-05-28 14:48 UTC, pazuzu-ua commented on beauty/api/views.py
> +        """This is a POST method of the view"""
I have rewritten it to have an ability to pass current user and user from the link into serializer. Couldn't find a better implementation as of now...

2022-05-30 08:41 UTC, Deer-WarLord commented on beauty/api/models.py
>          specialists = [position.specialists.all() for position in self.positions.all()]
Why don't you use just the specialist table to get them all?

2022-05-30 09:00 UTC, pazuzu-ua commented on beauty/api/models.py
>          specialists = [position.specialists.all() for position in self.positions.all()]
This is from our previous sprint, that was not coded by me. Someone was planning to use this method in the future tasks.

2022-06-01 08:21 UTC, Misha86 requested changes
Try to use fabrics into your tests

2022-06-01 08:23 UTC, Misha86 approved these changes

2022-06-01 10:24 UTC, morento101 commented on beauty/api/models.py
>          specialists = [position.specialists.all() for position in self.positions.all()]
I have rewritten that method in my pull request

2022-06-01 10:25 UTC, morento101 commented on beauty/api/models.py
>          verbose_name=_('Created at')
auto_now_add sets editable=False automaticaly

2022-06-01 10:27 UTC, morento101 approved these changes
Great job!

2022-06-01 17:40 UTC, morento101 commented on beauty/api/views.py
> +        """This is a POST method of the view"""
If you use CreateAPIView, your view will be reduced to 8 lines of code, including docstring

2022-06-02 09:15 UTC, therobotisnotatoy approved these changes

2022-06-02 11:21 UTC, merged