User story/#45 edit business info
ita-social-projects/BeatyProject pull request #183
Opened 2022-05-29 19:27 UTC by therobotisnotatoy

2022-05-31 14:07 UTC, Misha86 requested changes

2022-05-31 14:07 UTC, Misha86 commented on beauty/api/permissions.py
> +"""This module provides all needed permissions."""
need empty line after module docstring

2022-05-31 14:07 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +"""The module includes serializers for Business model."""
need empty line after module docstring

2022-05-31 14:07 UTC, Misha86 commented on beauty/api/views.py
> +"""This module provides all needed views."""
need empty line after module docstring

2022-05-31 14:07 UTC, Misha86 commented on beauty/api/views.py
> +        self.permission_classes = (IsAdminOrBusinessOwner,)
did you set permissions in line 134?

2022-06-01 10:33 UTC, morento101 commented on beauty/api/serializers/business_serializers.py
> +
Is there a need to write name and type fields if Django parses them from the model? You have listed these fields in class Meta.

2022-06-01 10:34 UTC, morento101 commented on beauty/api/serializers/business_serializers.py
> +        full_name = f"{obj.owner.first_name} {obj.owner.last_name}"
User model has method get_full_name()

2022-06-01 10:39 UTC, morento101 commented on beauty/api/serializers/business_serializers.py
> +
Does address change?  In DB address is implemented as a chain of tables. In the Business model, the address filed stores FK from the Address table. Can we store Varchar there?

2022-06-01 10:40 UTC, morento101 requested changes
Need to change some code

2022-06-01 14:39 UTC, closed without merging