#127 - Implement business serializer for getting all information
ita-social-projects/BeatyProject pull request #187
Opened 2022-05-30 13:51 UTC by shevchenkoira

Implemented business serializer for getting all information

2022-05-31 13:58 UTC, Misha86 requested changes
change type to business_type
empty line after module docstring

2022-05-31 13:58 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +import logging
empty line after module docstring

2022-05-31 13:58 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +    type = serializers.CharField(max_length=100) # noqa
change type to business_type

2022-05-31 13:58 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +        fields = ("name", "type", "address")
change type to business_type

2022-05-31 13:58 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +    def get_owner_name(self, obj):
need docstring

2022-06-02 15:40 UTC, pazuzu-ua requested changes
Good job! Just make those amendments per Mykhailo's suggestions

2022-06-06 21:19 UTC, shevchenkoira commented
Closes #127 #128 #126

2022-06-06 21:22 UTC, OleksiiDatsiuk approved these changes

2022-06-07 06:48 UTC, morento101 approved these changes
<html>
<body>
<!--StartFragment-->

:sunglasses:
--


<!--EndFragment-->
</body>
</html>

2022-06-07 07:30 UTC, pazuzu-ua approved these changes

2022-06-07 07:57 UTC, merged