#127 : Implement business get(RUD) view
ita-social-projects/BeatyProject pull request #188
Opened 2022-05-30 20:24 UTC by shevchenkoira

Create RUD view for business and overwrite get detail method

2022-05-30 20:38 UTC, pazuzu-ua approved these changes

2022-05-30 20:38 UTC, pazuzu-ua commented on beauty/api/views.py
> +        return get_object_or_404(self.queryset, id=instance.id)
please, add a new line

2022-05-31 06:45 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +    """Generic API for business GET, PUT and DELETE methods.
New line after class docstring needed.

2022-05-31 13:53 UTC, Misha86 requested changes
if you import more than one class from one module should use such syntactic (class, class, ...)

2022-05-31 13:53 UTC, Misha86 commented on beauty/api/views.py
> +from .models import CustomUser, Order, Business
if you import more than one class from one module should use such syntactic (class, class, ...)

2022-06-02 16:06 UTC, pazuzu-ua approved these changes

2022-06-02 23:55 UTC, OleksiiDatsiuk approved these changes

2022-06-03 08:03 UTC, Misha86 approved these changes

2022-06-03 08:03 UTC, merged