Feature #169 - Implement GET method view for the reviews
ita-social-projects/BeatyProject pull request #189
Opened 2022-05-31 00:39 UTC by OleksiiDatsiuk

I have implemented GET method view for the reviews, to be exact:

- Added default pagination class settings to the settings.py
- Implemented ReviewDisplayView view with GET method for retrieving reviews
- Added URL path to work with this view

Closes #169

2022-05-31 13:51 UTC, Misha86 requested changes
check your changes using flake8

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/urls.py
> +    path('<int:pk>/reviews/get/', ReviewDisplayView.as_view(),
need change URL such a way api/v1/reviews/<int:pk>/

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/views.py
> +from rest_framework.generics import RetrieveUpdateDestroyAPIView,\
if you import more than one class from one module should use such syntactic (class, class, ...)

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/views.py
> +from .models import CustomUser, Order, Review
if you import more than one class from one module should use such syntactic (class, class, ...)

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/views.py
> +    """Generic API for custom GET method"""
check your changes using flake8

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/views.py
> +    queryset = Review.objects
why queryset = Review.objects is not queryset = Review.objects.all()?

2022-05-31 13:51 UTC, Misha86 commented on beauty/api/views.py
> +    def get(self, request, *args, **kwargs):
What does this method reload?

2022-06-02 07:09 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +from .models import CustomUser, Order, Review
![image](https://user-images.githubusercontent.com/47336461/171573303-07456780-b368-493e-917f-dcb3a1e3087c.png)
My imports looks exactly like this, not sure what is wrong

2022-06-02 07:09 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +from .models import CustomUser, Order, Review
I've just added one more class to this list of imports, which were predefined before I started writing my tasks

2022-06-02 07:39 UTC, OleksiiDatsiuk commented
Still doesn't meet flake8 requirements will fix it later - right after writing the tests

2022-06-02 08:03 UTC, OleksiiDatsiuk commented on beauty/api/urls.py
> +    path('<int:pk>/reviews/get/', ReviewDisplayView.as_view(),
Got it

2022-06-02 08:03 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +from rest_framework.generics import RetrieveUpdateDestroyAPIView,\
Got it

2022-06-02 08:03 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +    queryset = Review.objects
Changed it

2022-06-02 11:38 UTC, Misha86 approved these changes

2022-06-02 14:48 UTC, merged