UserStory #22 - Display Info about Specialist
ita-social-projects/BeatyProject pull request #193
Opened 2022-05-31 17:47 UTC by shv833

#163 - ready for review
#164 - ready for review
#165 - closed(reason: needless)
#166 - ready for review

2022-05-31 17:58 UTC, morento101 commented on beauty/api/models.py
>      )
Why did you kill localization :sob:

2022-05-31 18:00 UTC, morento101 commented on beauty/api/serializers/serializers_customuser.py
Is that mean that now all users, including Owner and Client, will have a specialist_reviews field in views where this serializer is used?

2022-06-01 06:43 UTC, morento101 commented on beauty/api/models.py
>      )
Oh, now I understand, everything is good here

2022-06-01 08:00 UTC, Misha86 requested changes

2022-06-01 08:00 UTC, Misha86 commented on beauty/api/urls.py
> +    path('user/', CustomUserListCreateView.as_view(), name='user-list'),
should be "users/"

2022-06-04 10:03 UTC, pazuzu-ua requested changes
Please release all conflicts, ensure flake8 and all will be good!

2022-06-04 10:03 UTC, pazuzu-ua commented on beauty/api/urls.py
Please change the quotes to double

2022-06-07 19:02 UTC, pazuzu-ua approved these changes

2022-06-08 15:34 UTC, therobotisnotatoy approved these changes

2022-06-08 18:37 UTC, therobotisnotatoy approved these changes

2022-06-08 18:40 UTC, YaroslavBorysko approved these changes

2022-06-08 19:47 UTC, datsiuk-ira approved these changes

2022-06-08 19:50 UTC, Misha86 approved these changes

2022-06-08 19:53 UTC, morento101 approved these changes

2022-06-08 19:54 UTC, Serhii-Voloshyn approved these changes

2022-06-08 20:16 UTC, OleksiiDatsiuk approved these changes
Looks awesome!

2022-06-08 20:18 UTC, merged