UserStory #18 Create business
ita-social-projects/BeatyProject pull request #194
Opened 2022-05-31 19:36 UTC by morento101

User Story https://github.com/ita-social-projects/BeautyProject/issues/18

Closes https://github.com/ita-social-projects/BeautyProject/issues/123
Closes https://github.com/ita-social-projects/BeautyProject/issues/122
Closes https://github.com/ita-social-projects/BeautyProject/issues/124
Closes https://github.com/ita-social-projects/BeautyProject/issues/125

2022-06-01 07:58 UTC, Misha86 requested changes

2022-06-01 07:58 UTC, Misha86 commented on beauty/api/urls.py
> +    path('user/', CustomUserListCreateView.as_view(),
should be "users/"

2022-06-01 09:52 UTC, Serhii-Voloshyn commented on beauty/api/admin.py
> -
Docstring needed

2022-06-01 09:52 UTC, Serhii-Voloshyn commented on beauty/api/apps.py
>  class ApiConfig(AppConfig):
Docstring needed

2022-06-01 09:53 UTC, Serhii-Voloshyn commented on beauty/api/apps.py
> +        # signals.request_finished.connect(signals.my_callback)
If you don't need this code, delete it.

2022-06-01 09:54 UTC, Serhii-Voloshyn commented on beauty/api/forms.py
>      class Meta:
Add docstring

2022-06-01 09:54 UTC, Serhii-Voloshyn commented on beauty/api/forms.py
>      """A form for creating new users. Includes all the required
New line after class docstring.

2022-06-01 09:55 UTC, Serhii-Voloshyn commented on beauty/api/models.py
>          """This meta class stores verbose names ordering data"""
New line after docstring

2022-06-01 09:57 UTC, Serhii-Voloshyn commented on beauty/api/serializers/business_serializers.py
> +
2 new lines after import section needed

2022-06-01 09:58 UTC, Serhii-Voloshyn commented on beauty/api/serializers/order_serializers.py
> +
2 new lines after import section needed.

2022-06-01 09:59 UTC, Serhii-Voloshyn commented on beauty/api/tests/test_order_serializers.py
> +
2 new lines needed after import section.

2022-06-01 10:00 UTC, Serhii-Voloshyn commented on beauty/api/tests/test_order_views.py
> +
2 blank lines between import section and code.

2022-06-01 10:01 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +
2 blank lines between import section and code

2022-06-01 10:02 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +    # def get_permissions(self):
If you don't need this code -- delete it.

2022-06-01 10:03 UTC, Serhii-Voloshyn commented on beauty/beauty/signals.py
> +
2 blank lines between imports and code.

2022-06-01 10:04 UTC, Serhii-Voloshyn commented on beauty/beauty/tokens.py
> +
2 blank lines between imports and code.

2022-06-01 10:10 UTC, Serhii-Voloshyn reviewed
Also add docstring to business ListCreateView.

2022-06-01 10:55 UTC, morento101 commented on beauty/api/admin.py
> -
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 10:55 UTC, morento101 commented on beauty/api/apps.py
>  class ApiConfig(AppConfig):
Default django code

2022-06-01 10:55 UTC, morento101 commented on beauty/api/apps.py
> +        # signals.request_finished.connect(signals.my_callback)
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 10:55 UTC, morento101 commented on beauty/api/forms.py
>      class Meta:
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 10:55 UTC, morento101 commented on beauty/api/forms.py
>      """A form for creating new users. Includes all the required
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 10:56 UTC, morento101 commented on beauty/api/serializers/order_serializers.py
> +
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 10:56 UTC, morento101 commented on beauty/beauty/tokens.py
> +
Not my piece of code, I will try to fix it, but I don't guarantee

2022-06-01 18:56 UTC, therobotisnotatoy commented on beauty/beauty/utils.py
> +        2022, randint(1, 12), randint(1, 28), randint(0, 23),
Is there any simplest method to get a randomized date?
e.g.:

from faker import Faker
fake = Faker()

fake.date_between(start_date='today', end_date='+30y')

2022-06-02 11:37 UTC, Misha86 requested changes
use try-except block and .get() method

2022-06-02 11:37 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +        group = value.groups.filter(name="Owner").first()
use try-except block and .get() method (expert spoke about it)

2022-06-02 17:13 UTC, morento101 commented
Impleneted all your recomendations, check them :wink:

2022-06-02 18:32 UTC, Misha86 approved these changes
Good.

2022-06-02 18:34 UTC, pazuzu-ua approved these changes

2022-06-02 18:35 UTC, Serhii-Voloshyn approved these changes

2022-06-02 18:37 UTC, merged