UserStory #45 - edit business info
ita-social-projects/BeatyProject pull request #195
Opened 2022-06-01 18:32 UTC by therobotisnotatoy

Features #133 #134 #135 implemented.
Core style updated according to flake8 settings:
api/urls.py
api/views.py
api/permissions.py
beauty/urls.py

2022-06-01 20:48 UTC, morento101 commented on beauty/api/serializers/business_serializers.py
> +        logger.debug("Owner name transferred to frontend")
full_name = obj.owner.get_full_name()

2022-06-02 11:32 UTC, Misha86 requested changes

2022-06-02 11:32 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +        group = value.groups.filter(name="Owner").first()
use try-except  block and .get() method (expert spoke about it)

2022-06-02 11:32 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
>          owner = CustomUser.objects.filter(id=data["owner"]).first()
use .get() method

2022-06-02 11:32 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +    def get_owner_name(self, obj):
use to_representation() method.

2022-06-02 11:32 UTC, Misha86 commented on beauty/api/serializers/business_serializers.py
> +    owner_name = serializers.SerializerMethodField()
if you are using the to_representation() method you can delete this code string

2022-06-03 06:23 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +        group = value.groups.filter(name="Owner").first()
done

2022-06-03 06:25 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
>          owner = CustomUser.objects.filter(id=data["owner"]).first()
done

2022-06-03 06:31 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +    owner_name = serializers.SerializerMethodField()
done

2022-06-03 06:35 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +        logger.debug("Owner name transferred to frontend")
refactored according to others comments

2022-06-03 06:35 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +    def get_owner_name(self, obj):
done

2022-06-03 08:03 UTC, OleksiiDatsiuk approved these changes

2022-06-03 08:12 UTC, Misha86 approved these changes

2022-06-03 08:15 UTC, merged