Feature #130 - create serializer for position post method
ita-social-projects/BeatyProject pull request #200
Opened 2022-06-02 20:01 UTC by Serhii-Voloshyn

2022-06-03 08:06 UTC, Serhii-Voloshyn commented
Feature #130
Feature #129

2022-06-03 17:21 UTC, therobotisnotatoy requested changes

2022-06-03 17:21 UTC, therobotisnotatoy commented on beauty/api/serializers/position_serializer.py
> +logger = logging.getLogger(__name__)
Move standard library import before other imports. Add two empty lines after imports

2022-06-03 17:21 UTC, therobotisnotatoy commented on beauty/api/urls.py
> +                    OwnerBusinessDetailRUDView, ReviewAddView, PositionListCreateView)
Imports should be sorted alphabetically

2022-06-03 17:21 UTC, therobotisnotatoy commented on beauty/api/views.py
> +
In case this view is used only for position creation it should be restricted by permission, not by filtering

2022-06-03 17:27 UTC, Misha86 requested changes

2022-06-03 17:27 UTC, Misha86 commented on beauty/api/serializers/position_serializer.py
> +logger = logging.getLogger(__name__)
need 2 empty strings after import

2022-06-03 17:27 UTC, Misha86 commented on beauty/api/tests/test_position_POST_GET_view.py
> +from .factories import BusinessFactory, CustomUserFactory, GroupFactory, PositionFactory
use such syntactic making import (module, module ...)

2022-06-03 17:27 UTC, Misha86 commented on beauty/api/views.py
> +    permission_classes = (IsAuthenticated, )
Position can view only business owners and specialists. Is not it

2022-06-03 17:27 UTC, Misha86 commented on beauty/api/views.py
> +            return Position.objects.filter(business__in=[business.id for business in businesses])
look at subquery into the django for filter

2022-06-03 17:30 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +
Do you mean, I need to create permission class to check is user is Owner?

2022-06-03 19:03 UTC, Misha86 requested changes
use such syntactic making import (module, module ...)

2022-06-03 19:58 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +    permission_classes = (IsAuthenticated, )
I added permission IsPositionOwner to check it.

2022-06-03 19:58 UTC, Serhii-Voloshyn commented on beauty/api/views.py
> +            return Position.objects.filter(business__in=[business.id for business in businesses])
I added permission IsPositionOwner to check it.

2022-06-03 20:07 UTC, therobotisnotatoy approved these changes

2022-06-03 22:09 UTC, pazuzu-ua approved these changes

2022-06-04 11:14 UTC, Misha86 approved these changes

2022-06-04 11:14 UTC, merged