UserStory #25 - Display reviews
ita-social-projects/BeatyProject pull request #203
Opened 2022-06-02 23:50 UTC by OleksiiDatsiuk

I have implemented: 

- Serializer for displaying info about review
- View with GET method provided to get reviews for specified specialist
- Integration with flake8

TODO:

- Write tests for these methods

2022-06-03 11:28 UTC, morento101 commented on beauty/api/serializers/review_serializers.py
> +        fields = ("text_body",
fields = "__all__""

2022-06-03 11:29 UTC, morento101 commented on beauty/api/serializers/review_serializers.py
> +    def update(self, instance: object, validated_data: dict) -> object:
No need to overwrite the update method if you don't add any additional functionality

2022-06-03 11:32 UTC, morento101 commented on beauty/api/urls.py
> +    #      CustomUserOrderDetailRUDView.as_view(),
delete this piece of code, if it is useless

2022-06-03 11:34 UTC, morento101 commented on beauty/api/views.py
> -                                     RetrieveUpdateDestroyAPIView)
I don't understand the reason for deleting this

2022-06-03 11:35 UTC, morento101 commented on beauty/api/views.py
> +from .serializers.customuser_serializers import ResetPasswordSerializer
Uncomment or delete

2022-06-03 11:43 UTC, morento101 commented on beauty/beauty/urls.py
> +    #path(
Uncomment or delete

2022-06-03 11:47 UTC, morento101 commented on beauty/api/views.py
> +from .serializers.customuser_serializers import ResetPasswordSerializer
WET - we enjoy typing

2022-06-03 11:50 UTC, morento101 requested changes
In general, good, but some not critical changes needed

2022-06-03 22:18 UTC, pazuzu-ua requested changes

2022-06-03 22:18 UTC, pazuzu-ua commented on beauty/beauty/settings.py
> +        'rest_framework.pagination.LimitOffsetPagination',
flake8: please, add double quotes

2022-06-03 22:18 UTC, pazuzu-ua commented on beauty/api/serializers/review_serializers.py
> +class ReviewDisplayDetailSerializer(ReviewDisplaySerializer):
Will you add any functionality here? Is there a need in a distinct class?

2022-06-03 22:18 UTC, pazuzu-ua commented on beauty/api/views.py
> +            logger.info(f"Reviews for user with id {pk} were unsuccessfully obtained")
"were unsuccessfully obtained" means that you got the reviews, but you are not happy with that. Change to "failed to get reviews for user (...)"

2022-06-06 06:30 UTC, therobotisnotatoy requested changes

2022-06-06 06:30 UTC, therobotisnotatoy commented on beauty/api/urls.py
> +         name="review-get"),
I think this file is not up to date. Did you marge dev into your branch?

2022-06-06 06:30 UTC, therobotisnotatoy commented on beauty/api/views.py
> -                                     RetrieveUpdateDestroyAPIView)
I think this is part of old file version. Please be updated with develop branch

2022-06-06 21:05 UTC, OleksiiDatsiuk commented on beauty/api/serializers/review_serializers.py
> +        fields = ("text_body",
Got it

2022-06-06 21:05 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> -                                     RetrieveUpdateDestroyAPIView)
It is a part of older version of the project, fixed it by merging develop branch into mine

2022-06-06 21:05 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +from .serializers.customuser_serializers import ResetPasswordSerializer
Outdated

2022-06-06 21:05 UTC, OleksiiDatsiuk commented on beauty/beauty/urls.py
> +    #path(
Outdated

2022-06-06 21:07 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +from .serializers.customuser_serializers import ResetPasswordSerializer
Also was not my idea, I've got this, when merged develop branch into mine. The latest version doesn't include this code

2022-06-06 21:07 UTC, OleksiiDatsiuk commented on beauty/beauty/settings.py
> +        'rest_framework.pagination.LimitOffsetPagination',
Got it

2022-06-06 21:08 UTC, OleksiiDatsiuk commented on beauty/api/serializers/review_serializers.py
> +class ReviewDisplayDetailSerializer(ReviewDisplaySerializer):
For now - I am going to remove it in the next commit, cuz it is useless

2022-06-06 21:08 UTC, OleksiiDatsiuk commented on beauty/api/views.py
> +            logger.info(f"Reviews for user with id {pk} were unsuccessfully obtained")
Got it

2022-06-06 21:08 UTC, OleksiiDatsiuk commented on beauty/api/urls.py
> +         name="review-get"),
Yep, all of these files were not up to date, will fix it soon

2022-06-06 21:55 UTC, morento101 commented on .gitignore
>  .flake8
I have added those lines for ignoring my vscode project settings folder. I don't want to push them into our project repo.

Maybe, there is a reason for that?

2022-06-06 22:05 UTC, morento101 reviewed
Pls, don't kill .getkeep :innocent:

Fix pagination, add vscode in gitignore and I will approve this pull request

2022-06-07 09:47 UTC, shevchenkoira approved these changes

2022-06-07 10:01 UTC, therobotisnotatoy approved these changes

2022-06-07 10:14 UTC, pazuzu-ua commented on beauty/api/serializers/review_serializers.py
> +    text_body = serializers.CharField(max_length=500)
There is no need in them, as it appeared to be, so you can leave them =)

2022-06-07 10:14 UTC, pazuzu-ua commented on beauty/api/serializers/review_serializers.py
> +        """The save method to check whether users are trying to review themselves."""
Please, check that I have changed this method, don't override with an old version

2022-06-07 10:14 UTC, pazuzu-ua commented on beauty/api/tests/factories.py
> +    end_time = factory.LazyAttribute(lambda o: o.start_time - timezone.timedelta(hours=8))
Why it has "-"? End time should be later

2022-06-07 10:14 UTC, pazuzu-ua commented on beauty/api/tests/test_GET_method_to_get_reviews.py
> +        self.review = ReviewFactory.create(from_user=self.user, to_user=self.first_responder)
Why you do it 4 times in a row and assign to the same variable? If you need some of them to be in a db, just do a batch_create

2022-06-07 10:14 UTC, pazuzu-ua commented on beauty/api/tests/test_GET_method_to_get_reviews.py
> +        self.user = CustomUserFactory.create(is_active=True)
There is no more need in is_active, I have fixed the factory

2022-06-07 10:18 UTC, OleksiiDatsiuk commented
I have completely broken this pull request :) Will fix it soon

2022-06-07 10:28 UTC, closed without merging