Added custom command, added couple of fixes to factories
ita-social-projects/BeatyProject pull request #208
Opened 2022-06-04 21:59 UTC by pazuzu-ua

DO NOT MERGE UNTIL CHECKED

Added new custom command for populating db and for easier migration.

Usage:
- To add elements:
`python manage.py populate`
- To clear database before adding new items (IMPORTANT: it will flush your db, it will delete all entries, than it will perform migration - good for full reset of repo)
`python manage.py populate --force`
- To create superuser:
`python manage.py populate --superuser`

2022-06-05 08:04 UTC, Misha86 approved these changes
Approved

2022-06-05 20:58 UTC, morento101 approved these changes
Awesome!!!

2022-06-06 04:59 UTC, therobotisnotatoy requested changes

2022-06-06 04:59 UTC, therobotisnotatoy commented on beauty/api/management/commands/populate.py
> +            )
And if both random pk are the same? I believe it was told that user can not add review to itself.

2022-06-06 06:24 UTC, morento101 commented on beauty/api/management/commands/populate.py
> +            )
Will adding CustomUser SubFactories to ReviewFactory resolve this issue?

2022-06-06 08:57 UTC, pazuzu-ua commented on beauty/api/management/commands/populate.py
> +            )
In order to not to make extra people, rewrote it with choices.

2022-06-06 12:40 UTC, therobotisnotatoy approved these changes

2022-06-06 13:09 UTC, merged