Feature #162 - Created email verification for adding to Position
ita-social-projects/BeatyProject pull request #275
Opened 2022-06-18 15:31 UTC by pazuzu-ua

Hopefully closes #162 

Need your suggestions...

2022-06-19 07:56 UTC, Misha86 requested changes
Added some recommendations. If the code is working, no problem.

2022-06-19 07:56 UTC, Misha86 commented on beauty/api/views/position_views.py
> +        position_to_invite = Position.objects.get(pk=pk)
try it - position_to_invite = self.get_object(). I do not know if it works without queryset = Position.objects.all()

2022-06-19 07:56 UTC, Misha86 commented on beauty/api/serializers/position_serializer.py
> +        user = CustomUser.objects.filter(email=email_to_check)
Check user is specialist

2022-06-19 07:56 UTC, Misha86 commented on beauty/api/views/position_views.py
> +        serializer = PositionInviteSerializer(data=context)
Try to do context validation in the view class. Serializer uses only for email.

2022-06-19 07:56 UTC, Misha86 commented on beauty/api/views/position_views.py
> +    def put(self, request, pk, *args, **kwargs):
Maybe better use the post method? add queryset = Position.objects.all() and get position using self.get_object().

2022-06-19 08:16 UTC, morento101 commented on beauty/api/serializers/position_serializer.py
> +        return False
Artem gave the recommendation to stick to the "easier to apologize than ask permission".

But this is not a big deal, your code is good

2022-06-19 08:23 UTC, morento101 commented on beauty/api/views/position_views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
Interesting approach. 406 status code is used when a request does not have Accept header with a listed type of body response.

Maybe, there is a reason why you used it?

2022-06-19 08:28 UTC, morento101 commented on beauty/api/views/position_views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
It would be great to add some logging in this method

2022-06-19 08:30 UTC, morento101 commented on beauty/beauty/utils.py
> +        user = CustomUser.objects.get(email=email)
Is there a chance to get a CustomUser.DoesNotExist error? Maybe add try/except block?

2022-06-19 08:33 UTC, morento101 requested changes
Check my comments, if they are wrong, I will approve your request.

Waiting for your feedback:slightly_smiling_face:

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/api/serializers/position_serializer.py
> +        user = CustomUser.objects.filter(email=email_to_check)
Owner should be able to invite anyone to work for him. Still I have implemented a functionality that whenever user applies for the position, the user becomes a Specialist.

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/api/views/position_views.py
> +        serializer = PositionInviteSerializer(data=context)
Thank you for your help with code, the code was improved!

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/api/views/position_views.py
> +    def put(self, request, pk, *args, **kwargs):
Improved, thank you

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/api/serializers/position_serializer.py
> +        return False
Thank you!

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/api/views/position_views.py
> +            return Response(status=status.HTTP_400_BAD_REQUEST)
Returned back to 400

2022-06-19 14:36 UTC, pazuzu-ua commented on beauty/beauty/utils.py
> +        user = CustomUser.objects.get(email=email)
Thank you!

2022-06-19 15:47 UTC, Misha86 approved these changes
Review some recommendations. 
Good job.

2022-06-19 15:47 UTC, Misha86 commented on beauty/api/urls.py
> +        "position/<int:pk>/add",
add slash "position/<int:pk>/add/"

2022-06-19 15:47 UTC, Misha86 commented on beauty/api/views/position_views.py
> +    permission_classes = (IsAuthenticated & IsPositionOwner)
I got such error "OperandHolder' object is not iterable"  in the permission_classes

2022-06-19 15:47 UTC, Misha86 commented on beauty/api/views/position_views.py
> +            return Response(status=status.HTTP_200_OK)
delete one "return Response(status=status.HTTP_200_OK)" and rest one for whole method

2022-06-19 15:47 UTC, Misha86 commented on beauty/beauty/utils.py
> +        context.update(self.create_approve_link(user.id, pos, email))
try to use for less cod, it is recomandation.
context.update(self.create_approve_link(*context.values()). 
and string 144 - "user": encode_uid(inviter.id).

2022-06-20 07:19 UTC, shv833 requested changes
correct some links and add some blank lines😎

2022-06-20 07:19 UTC, shv833 commented on beauty/api/views/position_views.py
> +    queryset = Position.objects.all()
pls, add blank line after docstring of a class in every class:)

2022-06-21 11:59 UTC, Misha86 requested changes
View my recommendations.

2022-06-21 11:59 UTC, Misha86 commented on beauty/api/models.py
> +        validators=(validate_email,),
validate_email does not need because we use models.EmailField that includes it.

2022-06-21 11:59 UTC, Misha86 commented on beauty/api/serializers/customuser_serializers.py
> +class InviteUserCreate(PasswordsValidation, serializers.ModelSerializer):
Maybe better use inheritance from CustomUserSerializer?

2022-06-21 12:07 UTC, pazuzu-ua commented on beauty/api/serializers/customuser_serializers.py
> +class InviteUserCreate(PasswordsValidation, serializers.ModelSerializer):
That will include a lot of unneeded info from that class...

2022-06-21 15:48 UTC, morento101 commented on beauty/api/views/customuser_views.py
> +        """This method is used to register through an invitation.
Add logging to this method

2022-06-21 15:50 UTC, morento101 commented on beauty/api/models.py
> +        max_length=100,
add validators=(validate_email,),

2022-06-21 15:56 UTC, morento101 approved these changes
Approved, I hope you will add an email validator)))

UPD: no need for this validator

2022-06-21 15:57 UTC, morento101 commented on beauty/api/models.py
> +        max_length=100,
Oh, according to @Misha86 it is useless)))

2022-06-22 15:30 UTC, shevchenkoira requested changes

2022-06-22 15:30 UTC, shevchenkoira commented on beauty/api/admin.py
> +from api.models import CustomUser, Order, Service, Position, Business, Review, Invitation
please, make tuple here, when we import a few classes from one module we need to import it in tuple

2022-06-22 15:30 UTC, shevchenkoira commented on beauty/beauty/signals.py
> +from api.models import Order, Invitation
please, make tuple here, when we import a few classes from one module we need to import it in tuple

2022-06-22 19:23 UTC, shevchenkoira approved these changes

2022-06-22 19:47 UTC, shv833 approved these changes

2022-06-22 19:51 UTC, merged