feature/#256: Added tests for CustomerOrdersViews
ita-social-projects/BeatyProject pull request #276
Opened 2022-06-19 12:17 UTC by Misha86

Added tests for CustomerOrdersViews.

2022-06-19 14:41 UTC, pazuzu-ua approved these changes

2022-06-19 14:41 UTC, pazuzu-ua commented on beauty/api/tests/test_order_views.py
> +        """Logged users can not rearview a customer's orders."""
can't view

2022-06-21 20:35 UTC, morento101 approved these changes

2022-06-21 20:36 UTC, morento101 commented
You forgot to list new tests in module docstr

2022-06-22 19:41 UTC, shv833 requested changes

2022-06-22 19:41 UTC, shv833 commented on beauty/api/tests/test_order_views.py
>  from djoser.utils import encode_uid
as it was said by morento101, You forgot to list new tests in module docstr

2022-06-22 20:29 UTC, Misha86 commented on beauty/api/tests/test_order_views.py
>  from djoser.utils import encode_uid
Done

2022-06-22 20:53 UTC, shv833 approved these changes

2022-06-22 20:55 UTC, merged