Feature #253 - add working ours to our business
ita-social-projects/BeatyProject pull request #279
Opened 2022-06-21 14:38 UTC by Serhii-Voloshyn

Also added working time for position

2022-06-21 15:43 UTC, therobotisnotatoy approved these changes

2022-06-21 15:43 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +                    {day: "Day name not match main structure."},
If day name is missing in request?

2022-06-21 15:43 UTC, therobotisnotatoy commented on beauty/api/serializers/business_serializers.py
> +            if len(data[day]) == 2:
Please use variable from row 91. I forgot to change it.

2022-06-21 16:27 UTC, morento101 requested changes
Waiting for the all passing tests)))

2022-06-21 18:22 UTC, Serhii-Voloshyn commented on beauty/api/serializers/business_serializers.py
> +                    {day: "Day name not match main structure."},
This condition check day structure as string and if day is missing, so if day is missing, user will recieve error. It's essential to create business with all days defined.

2022-06-21 18:37 UTC, Serhii-Voloshyn commented on beauty/api/serializers/business_serializers.py
> +            if len(data[day]) == 2:
Done

2022-06-21 19:57 UTC, morento101 commented on beauty/api/serializers/position_serializer.py
> +        if len(business_time[time]) == len(data[time]) == 0:
Useless if statements, they do nothing. Just remove them.

Or maybe I'm wrong

2022-06-21 20:02 UTC, morento101 commented on beauty/api/serializers/position_serializer.py
> +
Maybe it is better to write so:
```py
if not inner_interval[0] < main_interval[0] and not inner_interval[1] > main_interval[1]:
    return True
```
But the line will be long...

2022-06-21 20:05 UTC, morento101 commented on beauty/api/tests/factories.py
> +        return self.business.working_time
So, the position will have the same schedule as a business. Not a problem, but I think it is better to generate an independent schedule for a position

2022-06-21 20:07 UTC, morento101 reviewed
Check my comments.

2022-06-21 20:11 UTC, morento101 commented on beauty/api/serializers/position_serializer.py
> +
Or there is another solution:
```py
if inner_interval[0] < main_interval[0] or inner_interval[1] > main_interval[1]:
    return False
return True
```

2022-06-21 21:27 UTC, Serhii-Voloshyn commented on beauty/api/serializers/position_serializer.py
> +        if len(business_time[time]) == len(data[time]) == 0:
It's needed, because next operations use list with length 2. So when we get list with 0 elements it throw an error without this condition.

2022-06-21 21:30 UTC, Serhii-Voloshyn commented on beauty/api/serializers/position_serializer.py
> +
flake8 didn't let me divide this condition into 2 strings. I will try again then.

2022-06-21 21:31 UTC, Serhii-Voloshyn commented on beauty/api/tests/factories.py
> +        return self.business.working_time
Yeah, I will remade this part and business too.

2022-06-22 08:22 UTC, morento101 approved these changes

2022-06-22 11:18 UTC, Serhii-Voloshyn commented on beauty/api/serializers/business_serializers.py
> +                      value[0],
It's not essential to save datetime to json using datetime, because it has same string format anyways.

2022-06-22 11:19 UTC, Serhii-Voloshyn commented on beauty/api/serializers/position_serializer.py
> +
I managed to use only one condition as return.

2022-06-22 13:18 UTC, OleksiiDatsiuk approved these changes

2022-06-22 13:22 UTC, merged