Fix #52 - Fix service views
ita-social-projects/BeatyProject pull request #280
Opened 2022-06-21 19:31 UTC by YaroslavBorysko

2022-06-21 20:24 UTC, morento101 commented on beauty/api/views_api.py
> +        specialist = CustomUser.objects.get(id=self.kwargs["pk"])
If a user or position with such id does not exist, the get method will raise CustomUser.DoesNotExist or Position.DoesNotExist error

You can use get_object_or_404, it will return 404 response :
```py
specialist = get_object_or_404(CustomUser, id=self.kwargs["pk"])
```

2022-06-21 20:26 UTC, morento101 commented on beauty/api/views_api.py
> +
Specialist can work in many businesses, you need to specify it to which display correct services

2022-06-21 20:28 UTC, morento101 reviewed
Hope, my comment are usefull

2022-06-22 08:24 UTC, morento101 commented on beauty/api/views_api.py
> +        position = Position.objects.get(specialist=specialist)
What if a position with such a specialist does not exist?

2022-06-22 08:25 UTC, morento101 commented on beauty/api/views_api.py
> +        position = Position.objects.get(business=business)
What if a business with such pk does not exist?

What if a position with such business does not exist?

2022-06-22 15:24 UTC, pazuzu-ua requested changes
Please, see  how your code behaves if the info is incorrect

2022-06-22 15:24 UTC, pazuzu-ua commented on beauty/api/views_api.py
> +        specialist = get_object_or_404(CustomUser, id=self.kwargs["pk"])
Do you catch this 404 in any way?

2022-06-23 08:12 UTC, closed without merging