Feature/#252 change add order endpoint for several orders
ita-social-projects/BeatyProject pull request #285
Opened 2022-06-22 15:06 UTC by Misha86

2022-06-22 15:40 UTC, pazuzu-ua approved these changes

2022-06-22 15:40 UTC, pazuzu-ua commented on beauty/api/serializers/order_serializers.py
> +            errors.update({"start_time": "The start time should be more as now."})
"should be later then now"

2022-06-22 15:40 UTC, pazuzu-ua commented on beauty/api/serializers/order_serializers.py
> +            logger.info("The start time should be more as now.")
"should be later then now"

2022-06-22 20:55 UTC, Misha86 commented on beauty/api/serializers/order_serializers.py
> +            errors.update({"start_time": "The start time should be more as now."})
Thanks.

2022-06-22 21:05 UTC, Misha86 commented on beauty/api/serializers/order_serializers.py
> +            logger.info("The start time should be more as now.")
done

2022-06-23 07:41 UTC, OleksiiDatsiuk approved these changes

2022-06-23 07:44 UTC, datsiuk-ira requested changes

2022-06-23 07:44 UTC, datsiuk-ira commented on beauty/api/tests/test_order_serializers.py
> +            "start_time": [ErrorDetail(string="The start time should be more as now.",
same as Dmytro mention

2022-06-23 08:40 UTC, Misha86 commented on beauty/api/tests/test_order_serializers.py
> +            "start_time": [ErrorDetail(string="The start time should be more as now.",
done

2022-06-23 08:42 UTC, shevchenkoira approved these changes

2022-06-23 08:43 UTC, merged