Feature #294 - Send an email message with issue request to the website's support
ita-social-projects/BeatyProject pull request #339
Opened 2022-06-30 11:38 UTC by YaroslavBorysko

2022-06-30 17:09 UTC, Misha86 requested changes
Use settings.EMAIL_HOST_USER to get email because when the admin changes email address will need to change it in your class too.

2022-06-30 17:09 UTC, Misha86 commented on beauty/api/views/contact_views.py
> +            send_mail(subject, req_template, "beautyproject689@gmail.com",
Maybe better get "beautyproject689@gmail.com" from settings.py?

2022-06-30 17:09 UTC, Misha86 commented on beauty/api/views/contact_views.py
> +            send_mail(subject, resp_template, "beautyproject689@gmail.com",
Maybe better get "[beautyproject689@gmail.com](mailto:beautyproject689@gmail.com)" from settings.py?

2022-06-30 17:09 UTC, Misha86 commented on beauty/api/views/contact_views.py
> +            send_mail(subject, resp_template, "beautyproject689@gmail.com",
settings.EMAIL_HOST_USER

2022-07-01 10:30 UTC, Misha86 approved these changes

2022-07-02 13:54 UTC, pazuzu-ua approved these changes

2022-07-02 14:34 UTC, shv833 approved these changes

2022-07-02 14:59 UTC, merged